<script lang="ts">
	import { onMount } from 'svelte';
	import FeedComponent from '../components/Feed.svelte';
	import Header from '../components/Header.svelte';
	import { feeds, type Feed } from '../feeds';
	import { Cluster, constructAutoFeed } from '../nlp';
	import { fetchRssFeed, type Item } from '../rss';

	let itemsByFeed: { [feed: string]: (Item | Cluster)[] } = {};

	const autoTopStoriesFeed: Feed = {
		source: 'feeder.news',
		section: '✨ Auto Top Stories',
		feed: 'feeder.news'
	};

	async function fetchFeeds() {
		const promises = feeds.map(async (feed) => {
			const items = await fetchRssFeed(feed);
			itemsByFeed[feed.feed] = items;
		});

		return Promise.all(promises);
	}

	onMount(async () => {
		await fetchFeeds();

		console.log({ feeds, itemsByFeed });

		// Done - do NLP
		itemsByFeed[autoTopStoriesFeed.feed] = constructAutoFeed(
			feeds,
			itemsByFeed as { [feed: string]: Item[] }
		);
		console.log(itemsByFeed[autoTopStoriesFeed.feed]);
	});
</script>

<Header />

<div class="flex overflow-x-auto">
	<FeedComponent
		feed={autoTopStoriesFeed}
		items={itemsByFeed[autoTopStoriesFeed.feed] ?? []}
		autogenerated={true}
	/>
	{#each feeds as feed}
		<FeedComponent {feed} items={itemsByFeed[feed.feed] ?? []} />
	{/each}
</div>
