<script lang="ts">
	import type { Feed } from '../feeds';
	import type { Cluster } from '../nlp';
	import type { Item } from '../rss';
	import ItemComponent from './Item.svelte';

	export let feed: Feed;

	export let items: (Item | Cluster)[] = [];
	export let autogenerated = false;
</script>

<div class="pane" class:bg-gray-800={autogenerated}>
	<div class="p-4 border-gray-600 border-b">
		<h1 class="font-bold text-md">{feed.source}</h1>
		<h2 class="text-sm text-gray-300">{feed.section}</h2>
	</div>
	<div class="overflow-y-auto pt-0">
		{#each items as itemOrCluster}
			<ItemComponent {itemOrCluster} />
		{/each}
	</div>
</div>
